---
title: "Group 8 - Lab 7"
author: "David Wiley"
date: "February 17, 2019"
output: pdf_document
---

## Lab 7

Using data from Problem 2.11 (from textbook). Test whether the true correlation is zero or not. 
Calculate the 90% CI. Interpret.


```{r, echo=FALSE}

# Reading in the information for Weight and Symbolic BP
dat=read.csv("C:\\Users\\Nick\\Documents\\0_Spring 2019\\Applied Regression\\Labs_HW\\Data_Sets\\Chapter 2\\Problems\\data-prob-2-10.csv", header = T)
y = dat[,2]
x = dat[,1]
n = length(x)

# Calculating variables
Sxx = sum(x^2) - sum(x)^2 / n
Sxy = sum(x*y) - sum(x)*sum(y) / n

B1H = Sxy / Sxx
B0H = mean(y) - mean(x)*B1H

yH = B0H + sort(x) * B1H

SSr = B1H * Sxy
SSres = sum((y - mean(y))^2) - SSr
  
SSt = SSr + SSres
MSres = SSres / (n-2)

seB1H = sqrt(MSres/Sxx)
seB0H = sqrt(MSres * (1 / n + mean(x)^2 / Sxx))

MSr = SSr/1

F0 = MSr / MSres

```
```{r}

# Estimating the correlation coefficient
r = Sxy / sqrt(Sxx * SSt)
r
R2 = SSr / SSt
R2

summary(lm(y~x))

#summary(lm(y~x-1))

```
## Testing true correlation

```{r}

plot(x,y)

qqnorm(resid(lm(y~x)))
qqline(resid(lm(y~x)))

cor.test(x,y, conf.level = .9)


```

## Interpretation:

Using the Pearson's product-moment correlation test, we can see that the true correlation is not equal to 0. 

The bounds for the %90 CI is 0.5954 to 0.8791.The correlation of 0.7735 falls within these bounds. 



